export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CATEGORY_FETCH = 'GET_CATEGORYLIST';
export const PERSONAL_INFO = 'GET_PERSONAL_INFORMATION';
export const CONTACT_DETAILS = 'CONTACT_DETAILS';

//User Management Actions
export const FARM_DETAILS = 'FARM_DETAILS';
export const CROP_DETAILS = 'CROP_DETAILS';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const FARMS_FETCH_SUCCESS = 'FARMS_FETCH_SUCCESS';
export const FETCH_FARMS_DETAILS = 'FETCH_FARMS_DETAILS';
