export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';




// Category ActionTypes
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_SPECIFIC_DATA_SUCCESS = 'CATEGORY_SPECIFIC_DATA_SUCCESS';

//Faq Action types
export const FAQ_CREATE_SUCCESS = 'FAQ_CREATE_SUCCESS';
export const FAQ_FETCH_SUCCESS = 'FAQ_FETCH_SUCCESS';
export const FAQ_UPDATE_SUCCESS = 'FAQ_UPDATE_SUCCESS'
export const FAQ_FETCH_SPECIFIC_DATA = 'FAQ_FETCH_SPECIFIC_DATA';
export const FAQ_DELETE_SUCCESS = 'FAQ_DELETE_SUCCESS';

//Coupon ActionTypes
export const COUPON_FETCH_SUCCESS = 'COUPON_FETCH_SUCCESS';
export const COUPON_CREATE_SUCCESS = 'COUPON_CREATE_SUCCESS';
export const COUPON_UPDATE_SUCCESS = 'COUPON_UPDATE_SUCCESS';
export const COUPON_DELETE_SUCCESS = 'COUPON_DELETE_SUCCESS';
export const COUPON_FETCH_SPECIFIC_DATA = 'COUPON_FETCH_SPECIFIC_DATA';


// Price ActionTypes

export const PRICE_FETCH_SUCCESS = 'PRICE_FETCH_SUCCESS ';
export const PRICE_CREATE_SUCCESS = 'PRICE_CREATE_SUCCESS';
export const PRICE_UPDATE_SUCCESS = 'PRICE_UPDATE_SUCCESS';
export const PRICE_DELETE_SUCCESS = 'PRICE_DELETE_SUCCESS';
export const PRICE_SPECIFIC_DATA_SUCCESS = 'PRICE_SPECIFIC_DATA_SUCCESS';
// import { CATEGORY_FETCH_SUCCESS, CATEGORY_CREATE_SUCCESS, CATEGORY_UPDATE_SUCCESS, CATEGORY_DELETE_SUCCESS, CATEGORY_SPECIFIC_DATA_SUCCESS

// Retailers ActionTypes
export const RETAILER_FETCH_SUCCESS = 'RETAILER_FETCH_SUCCESS';
export const RETAILER_CREATE_SUCCESS = 'RETAILER_CREATE_SUCCESS';
export const RETAILER_DELETE_SUCCESS = 'RETAILER_DELETE_SUCCESS';
export const RETAILER_UPDATE_SUCCESS = 'RETAILER_UPDATE_SUCCESS';
export const RET_COUNTRY_FETCH_SUCCESS = 'RET_COUNTRY_FETCH_SUCCESS';
export const RET_USER_FETCH_SUCCESS = 'RET_USER_FETCH_SUCCESS';

// RET_KYC ActionTypes
export const RET_KYC_FETCH_SUCCESS = 'RET_KYC_FETCH_SUCCESS';


export const PERSONAL_INFO = 'GET_PERSONAL_INFORMATION';
export const CONTACT_DETAILS = 'CONTACT_DETAILS';

export const UPDATE_CONTACT_DETAILS = 'UPDATE_CONTACT_DETAILS';
//User Management Actions
export const FARM_DETAILS = 'FARM_DETAILS';
export const CROP_DETAILS = 'CROP_DETAILS';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const KYC_DETAILS = 'KYC_DETAILS';
export const IRRIGATION_SCHEDULE = 'IRRIGATION_SCHEDULE';

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";
export const KYC_FETCH_SUCCESS = "KYC_FETCH_SUCCESS";
export const ADD_FARMDETAILS = 'ADD_FARMDETAILS';
export const UPDATE_FARMDETAILS = 'UPDATE_FARMDETAILS';

export const FARMS_FETCH_SUCCESS = 'FARMS_FETCH_SUCCESS';
export const FARMER_DELETE_SUCCESS = "FARMER_DELETE_SUCCESS";
export const FETCH_FARMS_DETAILS = 'FETCH_FARMS_DETAILS';
export const SET_USERS_LIST = 'SET_USERS_LIST';
export const SET_FARMS_LIST = 'SET_FARMS_LIST';
export const SET_FARMS_DETAILS = 'SET_FARMS_DETAILS';
export const GET_CROP_LIST = 'GET_CROP_LIST';

export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS';
export const ORDERDETAILS_FETCH_SUCCESS = 'ORDERDETAILS_FETCH_SUCCESS';
export const ORDERTRACK_FETCH_SUCCESS = 'ORDERTRACK_FETCH_SUCCESS';

export const IRRIGATION_SETTING_FETCH_SUCCESS = 'IRRIGATION_SETTING_FETCH_SUCCESS';
export const IRRIGATION_SETTING_SPECIFIC_DATA_SUCCESS = 'IRRIGATION_SETTING_SPECIFIC_DATA_SUCCESS';
export const IRRIGATION_SETTING_CREATE_SUCCESS = 'IRRIGATION_SETTING_CREATE_SUCCESS';
export const IRRIGATION_SETTING_UPDATE_SUCCESS = 'IRRIGATION_SETTING_UPDATE_SUCCESS';
export const IRRIGATION_SETTING_DELETE_SUCCESS = 'IRRIGATION_SETTING_DELETE_SUCCESS';

// Sales Agent ActionTypes
export const AGENT_FETCH_SUCCESS = 'AGENT_FETCH_SUCCESS';
export const AGENT_CREATE_SUCCESS = 'AGENT_CREATE_SUCCESS';
export const AGENT_UPDATE_SUCCESS = 'AGENT_UPDATE_SUCCESS';
export const AGENT_DELETE_SUCCESS = 'AGENT_DELETE_SUCCESS';
export const AGENT_SPECIFIC_DATA_SUCCESS = 'AGENT_SPECIFIC_DATA_SUCCESS';


export const VEHICLE_FETCH_SUCCESS = 'VEHICLE_FETCH_SUCCESS';
export const VEHICLE_SPECIFIC_DATA_SUCCESS = 'VEHICLE_SPECIFIC_DATA_SUCCESS';
export const VEHICLE_CREATE_SUCCESS = 'VEHICLE_CREATE_SUCCESS';
export const VEHICLE_UPDATE_SUCCESS = 'VEHICLE_UPDATE_SUCCESS';
export const VEHICLE_DELETE_SUCCESS = 'VEHICLE_DELETE_SUCCESS';

export const CUSIDLIST_FETCH_SUCCESS = 'CUSIDLIST_FETCH_SUCCESS';


